name: pmsn2023
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  table_calendar: ^3.0.9
  provider: ^6.0.5
  intl: ^0.18.1
  art_sweetalert: ^0.0.5
  http: ^1.1.0
  shared_preferences: ^2.2.1
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  day_night_switcher: ^0.2.0+1
  lottie: ^2.6.0
  concentric_transition: ^1.0.3
  flutter_local_notifications: ^16.1.0
  google_maps_flutter: ^2.5.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/.
    - assets/animation/.

